/* Sprites QuickC program
   By Jim Dose'  11/20/96
   Copyright (c)1996 Hipnotic Interactive, Inc.
   All rights reserved.
   Distributed (unsupported) on 3.12.97
*/

// Bullethole
$spritename s_bullet
$type oriented
$load h:/quake/hipwork/gfx/sprites/blood.lbm
$frame   96 16 8 8

// Blood Splat
$spritename s_blood1
$type oriented
$load h:/quake/hipwork/gfx/sprites/blood.lbm
$frame   32 32 56 56
